#!/bin/bash

build()
{
	# the following are stolen from the 'encrypt' hook
	local mod

	add_module "dm-crypt"
	if [[ $CRYPTO_MODULES ]]; then
		for mod in $CRYPTO_MODULES; do
			add_module "$mod"
		done
	else
		add_all_modules "/crypto/"
	fi

	if [ -d $BUILDROOT/etc/initcpio/gpg ]; then
		echo "WARNING! /etc/initcpio/gpg exists in initramfs buildroot. Huh?"
		rm -rf "$BUILDROOT/etc/initcpio/gpg"
	fi
	mkdir -p $BUILDROOT/etc/initcpio/gpg
	chmod 0700 $BUILDROOT/etc/initcpio/gpg

	# FIXME(ccruceru): can we do this by `add_file`?
	cp -r -T /home/calin/.gnupg $BUILDROOT/etc/initcpio/gpg
	cp /home/calin/.cryptswap.key $BUILDROOT/etc/initcpio/cryptswap.key
	
	add_binary "cryptsetup"
	add_binary "dmsetup"
	add_file "/usr/lib/udev/rules.d/10-dm.rules"
	add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
	add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
	add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"

	# cryptsetup calls pthread_create(), which dlopen()s libgcc_s.so.1
	add_binary "/usr/lib/libgcc_s.so.1"

	# gpg binaries
	add_binary "gpg"
	add_binary "gpg-agent"
	add_binary "pinentry-tty"
	add_binary "gpg-connect-agent"

	add_runscript
}

help()
{
	cat <<HELPEOF
This hook encrypts and decrypts the swap device only. It uses a GPG key file
stored at a fixed location on the unencrypted root filesystem. It prompts
the user for the GPG passphrase.
HELPEOF
}
